name: Build GeoSite

on:
  schedule:
    - cron: '0 1 * * 0'  # Каждое воскресенье в 01:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download latest geosite.dat from runetfreedom
        run: |
          curl -L -o geosite.dat https://github.com/runetfreedom/russia-blocked-geosite/releases/latest/download/geosite.dat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geosite.dat
          path: geosite.dat

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest GeoSite
          body: Автоматически загруженный файл geosite.dat из runetfreedom/russia-blocked-geosite
          files: geosite.dat
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
